# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e22b32ae0baa89e014ee31e831abf79a0068b342c7fdc15c6c605ae20224d4a7c95e1b6c4f3f12b046fcecb0c5bb92d6eb838af7a46fba6a0af1acaac5e9af07

test:
  secret_key_base: 8d6f495502e007d4a4b8f7d7b0d1489509dbb32cabd490de8ee88855bf2ddc24159af8f3a7c4c827d69818bc6641b14881416e1fc9857e408b432756b553b2e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
